//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOmework2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentsDB : DbContext
    {
        public studentsDB()
            : base("name=studentsDB")
        {
            
            Name name = new Name {  Name1 = "радиофизика" };
            Name name2 = new Name {  Name1 = "микроэлектроника" };
            Name name3 = new Name {  Name1 = "общая физика" };

            this.Names.Add(name);
            this.Names.Add(name2);
            this.Names.Add(name3);
            this.SaveChanges();
            

            Group g1 = new Group { Name_ID = 1, Number = 1 };
            Group g2 = new Group { Name_ID = 2, Number = 2 };
            Group g3 = new Group { Name_ID = 3, Number = 3 };

            this.Groups.Add(g1);
            this.Groups.Add(g2);
            this.Groups.Add(g3);
            this.SaveChanges();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Name> Names { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
